title: Stylish Portfolio, Start Bootstrap Template by startbootstrap.com
email: your-email@example.com
description: ""
author: ""

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - LICENSE
  - README.md
  - stylish-portfolio-.gif

# Social Profiles
twitter_username: ""
github_username: ""
facebook_username: ""
